### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by osenvosem** [matiastucci/vue-input-tag#6]
You didn't mark your [styles as `scoped`](https://github.com/matiastucci/vue-input-tag/blob/master/src/InputTag.vue#L78) does it mean that they are global?
[You change the `tags` property directly](https://github.com/matiastucci/vue-input-tag/blob/master/src/InputTag.vue#L36) while in documentation is said "you should not attempt to mutate a prop inside a child component." and use custom events instead.

I've just started to learn Vue.js, so could you please clarify these two things?

**Comment by tolerious** [comment]
1. I think `scoped` property is optional.
2. `You change the tags property directly`,  I think the author of `Vue.js` want you to mutate the `prop` data in child component through `Vuex`,  if the `prop` is an `Object`, after you change the value of the data, then its parent data also will change, if the `prop` is a `string`, after you change the value of the data, then its parent data won't change, so the author of `Vue.js` told you if you change the value of the prop string, it won' change the corresponding value in its parent.

**Comment by osenvosem** [comment]
@tolerious 
2. I understand that, but in the given case the author of the module change the object (array) received from the parent, directly in the child module.

**Comment by tolerious** [comment]
@osenvosem  sure, in my project if I don't use `Vuex`, I will use the `$emit(eventName)` and `$on(eventName)` to deliver the data.

**Comment by osenvosem** [comment]
@tolerious and this seems to be the right way, according the documentation. That is why I ask the author. 🙂

**Comment by matiastucci** [comment]
@osenvosem:

1. They are not global because all the styles are encapsulated under `.vue-input-tag-wrapper`. I'm not using `scoped` because it's a pain in the ass if you want to override the component styles.

2. In the docs it says: `This means you should not attempt to mutate a prop inside a child component. If you do, Vue will warn you in the console.` but I'm not seeing any warns.
But I think you're right, maybe it's better to avoid doing that. I'll change that soon.

@tolerious: thanks for helping me answer :)

**Comment by osenvosem** [comment]
@matiastucci thank you for the answer.
